#!/bin/sh

sxhkd &

bspc monitor -d term web work music misc

bspc config border_width          3
bspc config focused_border_color  "#ff9000"
bspc config window_gap            12
bspc config top_padding           30

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Chromium desktop='^2'
bspc rule -a Chromium:player.spotify.com desktop='^4' follow=on
bspc rule -a Xournal desktop='^3' follow=on

urxvt -lsp 1 &

bar &
