#!/bin/sh

sxhkd &

bspc monitor -d term web work music misc

bspc config border_width          3
bspc config focused_border_color  "#ff9000"
bspc config window_gap            12
bspc config top_padding           30

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config click_to_focus button1

bspc config external_rules_command "$HOME/.config/bspwm/ext_rules"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Firefox desktop='^2'
# bspc rule -a Chromium:player.spotify.com desktop='^4' follow=on
bspc rule -a Spotify desktop='^4' follow=on
bspc rule -a Xournal desktop='^3' follow=on

termite &

bar &
